var e="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},g="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function k(){k=function(){};g.Symbol||(g.Symbol=l)}var n=0;function l(a){return"jscomp_symbol_"+(a||"")+n++}
function p(){k();var a=g.Symbol.iterator;a||(a=g.Symbol.iterator=g.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&e(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return q(this)}});p=function(){}}function q(a){var b=0;return r(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function r(a){p();a={next:a};a[g.Symbol.iterator]=function(){return this};return a}function v(a){p();var b=a[Symbol.iterator];return b?b.call(a):q(a)}
function w(a){if(!(a instanceof Array)){a=v(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a};function z(){this.h=document.getElementById("canvas");this.i=document.getElementById("wrapper");this.c=new A;this.b=new B;this.f=new C;this.a=new D;this.g=new E}function A(){this.c=document.getElementById("home-button");this.a=document.getElementById("about-button");this.b=document.getElementById("bio-button");this.f=document.getElementById("projects-button")}
function B(){this.h=document.getElementById("home-button-text");this.a=document.getElementById("about-button-text");this.b=document.getElementById("bio-button-text");this.m=document.getElementById("projects-button-text");this.s=document.getElementById("website-button-text");this.g=document.getElementById("hemophilia-button-text");this.l=document.getElementById("probabilities-button-text");this.o=document.getElementById("pygquery-button-text");this.f=document.getElementById("builder-button-text");
this.c=document.getElementById("books-button-text");this.i=document.getElementById("music-button-text");this.j=document.getElementById("other-button-text")}function C(){this.a=document.getElementById("about-page");this.b=document.getElementById("bio-page");this.c=document.getElementById("projects-page")}
function D(){this.a=document.getElementById("projects");this.l=document.getElementById("website");this.b=document.getElementById("hemophilia");this.c=document.getElementById("probabilities");this.j=document.getElementById("pygquery");this.g=document.getElementById("builder");this.f=document.getElementById("books");this.h=document.getElementById("music");this.i=document.getElementById("other")}
function E(){this.a=document.getElementById("full-hemophilia");this.b=document.getElementById("full-probabilities")};function F(a){this.g=a;this.a=a.getContext("2d");this.c="white";this.h="black";this.b=2}F.prototype.f=function(){this.g.style.backgroundColor=this.c;this.a.shadowColor=""};function G(a,b,c){a.a.beginPath();a.a.arc(b,c,20,0,2*Math.PI);a.a.lineWidth=a.b;a.a.strokeStyle=a.h;a.a.stroke();a.a.closePath()}function H(a,b,c){a.a.beginPath();a.a.arc(b,c,20,0,2*Math.PI);a.a.lineWidth=a.b+5;a.a.strokeStyle="white";a.a.stroke();a.a.closePath()};function I(a,b,c){this.a=a;this.c=b;this.b=c}
I.prototype.f=function(){var a=this;J(this);K(this);window.addEventListener("click",function(b){b=v([b.clientX,b.clientY]);var c=b.next().value,d=b.next().value;G(a.c,c,d);setTimeout(function(){H(a.c,c,d)},5E3);L(a.b,0,c,d)});window.addEventListener("resize",function(){J(a);K(a)});this.a.c.c.addEventListener("click",function(){M(a)});this.a.c.c.addEventListener("mouseover",function(){N(a);a.a.b.h.style.fontWeight="bold"});this.a.c.a.addEventListener("click",function(){M(a);a.a.f.a.style.display="inline-block"});
this.a.c.a.addEventListener("mouseover",function(){N(a);a.a.b.a.style.fontWeight="bold"});this.a.c.b.addEventListener("click",function(){M(a);a.a.f.b.style.display="inline-block"});this.a.c.b.addEventListener("mouseover",function(){N(a);a.a.b.b.style.fontWeight="bold"});this.a.c.f.addEventListener("click",function(){M(a);for(var b=v(Object.values(a.a.g)),c=b.next();!c.done;c=b.next())c.value.style.display="none";a.a.f.c.style.display="inline-block";a.a.a.a.style.display="flex"});this.a.c.f.addEventListener("mouseover",
function(){N(a);a.a.b.m.style.fontWeight="bold"});this.a.a.l.addEventListener("mouseover",function(){N(a);a.a.b.s.style.fontWeight="bold"});this.a.a.b.addEventListener("click",function(){a.a.a.a.style.display="none";a.a.g.a.style.display="inline-block"});this.a.a.b.addEventListener("mouseover",function(){N(a);a.a.b.g.style.fontWeight="bold"});this.a.a.c.addEventListener("click",function(){a.a.a.a.style.display="none";a.a.g.b.style.display="inline-block"});this.a.a.c.addEventListener("mouseover",function(){N(a);
a.a.b.l.style.fontWeight="bold"});this.a.a.j.addEventListener("mouseover",function(){N(a);a.a.b.o.style.fontWeight="bold"});this.a.a.g.addEventListener("mouseover",function(){N(a);a.a.b.f.style.fontWeight="bold"});this.a.a.f.addEventListener("mouseover",function(){N(a);a.a.b.c.style.fontWeight="bold"});this.a.a.h.addEventListener("mouseover",function(){N(a);a.a.b.i.style.fontWeight="bold"});this.a.a.i.addEventListener("mouseover",function(){N(a);a.a.b.j.style.fontWeight="bold"});window.addEventListener("mousemove",
function(b){b=v(O(a.b,b.clientX,b.clientY));for(var c=b.next();!c.done;c=b.next()){var d=v(c.value),c=d.next().value,d=d.next().value;G(a.c,c,d);L(a.b,1,c,d);setTimeout(function(){var b=a.b;b.a[1]=b.a[1]||[];var c=v([b.a[1].shift(),b.a[1].shift()]),d=c.next().value,c=c.next().value,d=v([d+b.b/2,c]),b=d.next().value,d=d.next().value;H(a.c,b,d);K(a)},500)}})};function M(a){a=v(Object.values(a.a.f));for(var b=a.next();!b.done;b=a.next())b.value.style.display="none"}
function N(a){a=v(Object.values(a.a.b));for(var b=a.next();!b.done;b=a.next())b.value.style.fontWeight="normal"}function K(a){for(var b=v([0,1]),c=b.next();!c.done;c=b.next())for(var c=v(P(a.b,c.value)),d=c.next();!d.done;d=c.next())d=d.value,G(a.c,d[0],d[1])}function J(a){var b=a.a.h,c=a.a.i,c=v([c.clientWidth,c.clientHeight]);a.h=c.next().value;a.g=c.next().value;c=v([a.h,a.g]);b.width=c.next().value;b.height=c.next().value;b=a.b;c=a.g;b.b=a.h;b.g=c};function Q(){var a=this;this.a=[];this.c=[10,100];this.h=function(b){return Math.pow(Math.E,-Math.pow((b-a.b/2)/(a.b/4),2))};this.i=function(b){return-b/a.g+1}}Q.prototype.f=function(){};function L(a,b,c,d){a.a[b]=a.a[b]||[];a.a[b].push.apply(a.a[b],[].concat(w([c-a.b/2,d])))}
function P(a,b){function c(a){for(;;)switch(d){case 0:h.a[b]=h.a[b]||[],f=0;case 1:if(!(f<h.a[b].length)){d=3;break}d=4;return{value:[h.a[b][f]+h.b/2,h.a[b][f+1]],done:!1};case 4:if(void 0===a){d=5;break}d=-1;throw a;case 5:case 2:f+=2;d=1;break;case 3:d=-1;default:return{value:void 0,done:!0}}}var d=0,f,h=a,m={next:function(){return c(void 0)},"throw":function(a){return c(a)},"return":function(){throw Error("Not yet implemented");}};p();m[Symbol.iterator]=function(){return this};return m}
function O(a,b,c){function d(a){for(;;)switch(f){case 0:y=0;case 1:if(!(4>y)){f=3;break}var d=t,W=c,u=R(d.h,b),d=R(d.i,W);x=v([u,d]);m=x.next().value;h=x.next().value;if(!m||!h){f=4;break}f=5;a=Math.random()*(t.c[1]-t.c[0])+t.c[0];u=2*Math.random()*Math.PI;return{value:[m+a*Math.cos(u),h+a*Math.sin(u)],done:!1};case 5:if(void 0===a){f=6;break}f=-1;throw a;case 6:case 4:case 2:y++;f=1;break;case 3:f=-1;default:return{value:void 0,done:!0}}}var f=0,h,m,x,y,t=a;a={next:function(){return d(void 0)},"throw":function(a){return d(a)},
"return":function(){throw Error("Not yet implemented");}};p();a[Symbol.iterator]=function(){return this};return a}function R(a,b){if(1*Math.random()<Math.abs(a(b)))return b};function S(){for(var a=new z,b=new F(a.h),c=new Q,a=v([b,c,new I(a,b,c)]),b=a.next();!b.done;b=a.next())b.value.f()}var T=["main"],U=this;T[0]in U||!U.execScript||U.execScript("var "+T[0]);for(var V;T.length&&(V=T.shift());)T.length||void 0===S?U[V]?U=U[V]:U=U[V]={}:U[V]=S;S();
